In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [3]:
df = pd.read_csv('hiring.csv')
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   experience       6 non-null      object 
 1   test_score       7 non-null      float64
 2   interview_score  8 non-null      int64  
 3   salary           8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [ ]:
df.isnull().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [ ]:
df['test_score'].mean()

7.857142857142857

In [4]:
df['test_score'].fillna(df['test_score'].mean(),inplace=True)

In [5]:
df.isnull().sum()

experience         2
test_score         0
interview_score    0
salary             0
dtype: int64

In [6]:
df.head()

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [7]:
df['experience'].fillna(0,inplace=True)

In [8]:
df.isnull().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

In [9]:
def convert_to_int(word):
    word_dict = {'one':1, 'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'seven':7, 'eight':8,
                'nine':9, 'ten':10, 'eleven':11, 'twelve':12, 'zero':0, 0: 0}
    return word_dict[word]

In [10]:
X = df.iloc[:,:3]
X

experience  test_score  interview_score
0          0    8.000000                9
1          0    8.000000                6
2       five    6.000000                7
3        two   10.000000               10
4      seven    9.000000                6
5      three    7.000000               10
6        ten    7.857143                7
7     eleven    7.000000                8

In [11]:
y = df['salary'].values
y

array([50000, 45000, 60000, 65000, 70000, 62000, 72000, 80000])

In [12]:
X['experience'] = X['experience'].apply(lambda x : convert_to_int(x))

In [14]:
X.values

array([[ 0.        ,  8.        ,  9.        ],
       [ 0.        ,  8.        ,  6.        ],
       [ 5.        ,  6.        ,  7.        ],
       [ 2.        , 10.        , 10.        ],
       [ 7.        ,  9.        ,  6.        ],
       [ 3.        ,  7.        , 10.        ],
       [10.        ,  7.85714286,  7.        ],
       [11.        ,  7.        ,  8.        ]])

In [15]:

y

array([50000, 45000, 60000, 65000, 70000, 62000, 72000, 80000])

In [13]:
from sklearn.linear_model import LinearRegression

In [17]:
regressor = LinearRegression()


In [18]:
regressor.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
regressor.predict([[2,4,5]])

array([41529.22709267])

In [20]:
# from joblib import dump,load

In [25]:
import pickle 

In [26]:
pickle.dump(regressor,open('model.pkl','wb'))

In [27]:
model_ml = pickle.load(open('model.pkl','rb'))

In [28]:
model_ml.predict([[2,3,4]])

array([37419.31374803])